#ifndef GUARD_VMP_OPCODE_DEF_H
#define GUARD_VMP_OPCODE_DEF_H

// =====================================================
// Dalvik / Dex Opcode 定义
// =====================================================

#define OP_NOP                            0x00
#define OP_MOVE                           0x01
#define OP_MOVE_FROM16                    0x02
#define OP_MOVE_16                        0x03
#define OP_MOVE_WIDE                      0x04
#define OP_MOVE_WIDE_FROM16               0x05
#define OP_MOVE_WIDE_16                   0x06
#define OP_MOVE_OBJECT                    0x07
#define OP_MOVE_OBJECT_FROM16             0x08
#define OP_MOVE_OBJECT_16                 0x09
#define OP_MOVE_RESULT                    0x0a
#define OP_MOVE_RESULT_WIDE               0x0b
#define OP_MOVE_RESULT_OBJECT             0x0c
#define OP_MOVE_EXCEPTION                 0x0d
#define OP_RETURN_VOID                    0x0e
#define OP_RETURN                         0x0f
#define OP_RETURN_WIDE                    0x10
#define OP_RETURN_OBJECT                  0x11
#define OP_CONST_4                        0x12
#define OP_CONST_16                       0x13
#define OP_CONST                          0x14
#define OP_CONST_HIGH16                   0x15
#define OP_CONST_WIDE_16                  0x16
#define OP_CONST_WIDE_32                  0x17
#define OP_CONST_WIDE                     0x18
#define OP_CONST_WIDE_HIGH16              0x19
#define OP_CONST_STRING                   0x1a
#define OP_CONST_STRING_JUMBO             0x1b
#define OP_CONST_CLASS                    0x1c
#define OP_MONITOR_ENTER                  0x1d
#define OP_MONITOR_EXIT                   0x1e
#define OP_CHECK_CAST                     0x1f
#define OP_INSTANCE_OF                    0x20
#define OP_ARRAY_LENGTH                   0x21
#define OP_NEW_INSTANCE                   0x22
#define OP_NEW_ARRAY                      0x23
#define OP_FILLED_NEW_ARRAY               0x24
#define OP_FILLED_NEW_ARRAY_RANGE         0x25
#define OP_FILL_ARRAY_DATA                0x26 //需要做测试，此时改动了bin生成方法
#define OP_THROW                          0x27
#define OP_GOTO                           0x28
#define OP_GOTO_16                        0x29
#define OP_GOTO_32                        0x2a
#define OP_PACKED_SWITCH                  0x2b //需要做测试，此时改动了bin生成方法
#define OP_SPARSE_SWITCH                  0x2c //需要做测试，此时改动了bin生成方法
#define OP_CMPL_FLOAT                     0x2d
#define OP_CMPG_FLOAT                     0x2e
#define OP_CMPL_DOUBLE                    0x2f
#define OP_CMPG_DOUBLE                    0x30
#define OP_CMP_LONG                       0x31
#define OP_IF_EQ                          0x32
#define OP_IF_NE                          0x33
#define OP_IF_LT                          0x34
#define OP_IF_GE                          0x35
#define OP_IF_GT                          0x36
#define OP_IF_LE                          0x37
#define OP_IF_EQZ                         0x38
#define OP_IF_NEZ                         0x39
#define OP_IF_LTZ                         0x3a
#define OP_IF_GEZ                         0x3b
#define OP_IF_GTZ                         0x3c
#define OP_IF_LEZ                         0x3d
#define OP_UNUSED_3E                      0x3e
#define OP_UNUSED_3F                      0x3f
#define OP_UNUSED_40                      0x40
#define OP_UNUSED_41                      0x41
#define OP_UNUSED_42                      0x42
#define OP_UNUSED_43                      0x43
#define OP_AGET                           0x44
#define OP_AGET_WIDE                      0x45
#define OP_AGET_OBJECT                    0x46
#define OP_AGET_BOOLEAN                   0x47
#define OP_AGET_BYTE                      0x48
#define OP_AGET_CHAR                      0x49
#define OP_AGET_SHORT                     0x4a
#define OP_APUT                           0x4b
#define OP_APUT_WIDE                      0x4c
#define OP_APUT_OBJECT                    0x4d
#define OP_APUT_BOOLEAN                   0x4e
#define OP_APUT_BYTE                      0x4f
#define OP_APUT_CHAR                      0x50
#define OP_APUT_SHORT                     0x51
#define OP_IGET                           0x52
#define OP_IGET_WIDE                      0x53
#define OP_IGET_OBJECT                    0x54
#define OP_IGET_BOOLEAN                   0x55
#define OP_IGET_BYTE                      0x56
#define OP_IGET_CHAR                      0x57
#define OP_IGET_SHORT                     0x58
#define OP_IPUT                           0x59
#define OP_IPUT_WIDE                      0x5a
#define OP_IPUT_OBJECT                    0x5b
#define OP_IPUT_BOOLEAN                   0x5c
#define OP_IPUT_BYTE                      0x5d
#define OP_IPUT_CHAR                      0x5e
#define OP_IPUT_SHORT                     0x5f
#define OP_SGET                           0x60
#define OP_SGET_WIDE                      0x61
#define OP_SGET_OBJECT                    0x62
#define OP_SGET_BOOLEAN                   0x63
#define OP_SGET_BYTE                      0x64
#define OP_SGET_CHAR                      0x65
#define OP_SGET_SHORT                     0x66
#define OP_SPUT                           0x67
#define OP_SPUT_WIDE                      0x68
#define OP_SPUT_OBJECT                    0x69
#define OP_SPUT_BOOLEAN                   0x6a
#define OP_SPUT_BYTE                      0x6b
#define OP_SPUT_CHAR                      0x6c
#define OP_SPUT_SHORT                     0x6d
#define OP_INVOKE_VIRTUAL                 0x6e
#define OP_INVOKE_SUPER                   0x6f
#define OP_INVOKE_DIRECT                  0x70
#define OP_INVOKE_STATIC                  0x71
#define OP_INVOKE_INTERFACE               0x72
#define OP_UNUSED_73                      0x73
#define OP_INVOKE_VIRTUAL_RANGE           0x74
#define OP_INVOKE_SUPER_RANGE             0x75
#define OP_INVOKE_DIRECT_RANGE            0x76
#define OP_INVOKE_STATIC_RANGE            0x77
#define OP_INVOKE_INTERFACE_RANGE         0x78
#define OP_UNUSED_79                      0x79
#define OP_UNUSED_7A                      0x7a
#define OP_NEG_INT                        0x7b
#define OP_NOT_INT                        0x7c
#define OP_NEG_LONG                       0x7d
#define OP_NOT_LONG                       0x7e
#define OP_NEG_FLOAT                      0x7f
#define OP_NEG_DOUBLE                     0x80
#define OP_INT_TO_LONG                    0x81
#define OP_INT_TO_FLOAT                   0x82
#define OP_INT_TO_DOUBLE                  0x83
#define OP_LONG_TO_INT                    0x84
#define OP_LONG_TO_FLOAT                  0x85
#define OP_LONG_TO_DOUBLE                 0x86
#define OP_FLOAT_TO_INT                   0x87
#define OP_FLOAT_TO_LONG                  0x88
#define OP_FLOAT_TO_DOUBLE                0x89
#define OP_DOUBLE_TO_INT                  0x8a
#define OP_DOUBLE_TO_LONG                 0x8b
#define OP_DOUBLE_TO_FLOAT                0x8c
#define OP_INT_TO_BYTE                    0x8d
#define OP_INT_TO_CHAR                    0x8e
#define OP_INT_TO_SHORT                   0x8f
#define OP_ADD_INT                        0x90
#define OP_SUB_INT                        0x91
#define OP_MUL_INT                        0x92
#define OP_DIV_INT                        0x93
#define OP_REM_INT                        0x94
#define OP_AND_INT                        0x95
#define OP_OR_INT                         0x96
#define OP_XOR_INT                        0x97
#define OP_SHL_INT                        0x98
#define OP_SHR_INT                        0x99
#define OP_USHR_INT                       0x9a
#define OP_ADD_LONG                       0x9b
#define OP_SUB_LONG                       0x9c
#define OP_MUL_LONG                       0x9d
#define OP_DIV_LONG                       0x9e
#define OP_REM_LONG                       0x9f
#define OP_AND_LONG                       0xa0
#define OP_OR_LONG                        0xa1
#define OP_XOR_LONG                       0xa2
#define OP_SHL_LONG                       0xa3
#define OP_SHR_LONG                       0xa4
#define OP_USHR_LONG                      0xa5
#define OP_ADD_FLOAT                      0xa6
#define OP_SUB_FLOAT                      0xa7
#define OP_MUL_FLOAT                      0xa8
#define OP_DIV_FLOAT                      0xa9
#define OP_REM_FLOAT                      0xaa
#define OP_ADD_DOUBLE                     0xab
#define OP_SUB_DOUBLE                     0xac
#define OP_MUL_DOUBLE                     0xad
#define OP_DIV_DOUBLE                     0xae
#define OP_REM_DOUBLE                     0xaf
#define OP_ADD_INT_2ADDR                  0xb0
#define OP_SUB_INT_2ADDR                  0xb1
#define OP_MUL_INT_2ADDR                  0xb2
#define OP_DIV_INT_2ADDR                  0xb3
#define OP_REM_INT_2ADDR                  0xb4
#define OP_AND_INT_2ADDR                  0xb5
#define OP_OR_INT_2ADDR                   0xb6
#define OP_XOR_INT_2ADDR                  0xb7
#define OP_SHL_INT_2ADDR                  0xb8
#define OP_SHR_INT_2ADDR                  0xb9
#define OP_USHR_INT_2ADDR                 0xba
#define OP_ADD_LONG_2ADDR                 0xbb
#define OP_SUB_LONG_2ADDR                 0xbc
#define OP_MUL_LONG_2ADDR                 0xbd
#define OP_DIV_LONG_2ADDR                 0xbe
#define OP_REM_LONG_2ADDR                 0xbf
#define OP_AND_LONG_2ADDR                 0xc0
#define OP_OR_LONG_2ADDR                  0xc1
#define OP_XOR_LONG_2ADDR                 0xc2
#define OP_SHL_LONG_2ADDR                 0xc3
#define OP_SHR_LONG_2ADDR                 0xc4
#define OP_USHR_LONG_2ADDR                0xc5
#define OP_ADD_FLOAT_2ADDR                0xc6
#define OP_SUB_FLOAT_2ADDR                0xc7
#define OP_MUL_FLOAT_2ADDR                0xc8
#define OP_DIV_FLOAT_2ADDR                0xc9
#define OP_REM_FLOAT_2ADDR                0xca
#define OP_ADD_DOUBLE_2ADDR               0xcb
#define OP_SUB_DOUBLE_2ADDR               0xcc
#define OP_MUL_DOUBLE_2ADDR               0xcd
#define OP_DIV_DOUBLE_2ADDR               0xce
#define OP_REM_DOUBLE_2ADDR               0xcf
#define OP_ADD_INT_LIT16                  0xd0
#define OP_RSUB_INT                       0xd1
#define OP_MUL_INT_LIT16                  0xd2
#define OP_DIV_INT_LIT16                  0xd3
#define OP_REM_INT_LIT16                  0xd4
#define OP_AND_INT_LIT16                  0xd5
#define OP_OR_INT_LIT16                   0xd6
#define OP_XOR_INT_LIT16                  0xd7
#define OP_ADD_INT_LIT8                   0xd8
#define OP_RSUB_INT_LIT8                  0xd9
#define OP_MUL_INT_LIT8                   0xda
#define OP_DIV_INT_LIT8                   0xdb
#define OP_REM_INT_LIT8                   0xdc
#define OP_AND_INT_LIT8                   0xdd
#define OP_OR_INT_LIT8                    0xde
#define OP_XOR_INT_LIT8                   0xdf
#define OP_SHL_INT_LIT8                   0xe0
#define OP_SHR_INT_LIT8                   0xe1
#define OP_USHR_INT_LIT8                  0xe2
#define OP_UNUSED_E3                      0xe3
#define OP_UNUSED_E4                      0xe4
#define OP_UNUSED_E5                      0xe5
#define OP_UNUSED_E6                      0xe6
#define OP_UNUSED_E7                      0xe7
#define OP_UNUSED_E8                      0xe8
#define OP_UNUSED_E9                      0xe9
#define OP_UNUSED_EA                      0xea
#define OP_UNUSED_EB                      0xeb
#define OP_UNUSED_EC                      0xec
#define OP_UNUSED_ED                      0xed
#define OP_UNUSED_EE                      0xee
#define OP_UNUSED_EF                      0xef
#define OP_UNUSED_F0                      0xf0
#define OP_UNUSED_F1                      0xf1
#define OP_UNUSED_F2                      0xf2
#define OP_UNUSED_F3                      0xf3
#define OP_UNUSED_F4                      0xf4
#define OP_UNUSED_F5                      0xf5
#define OP_UNUSED_F6                      0xf6
#define OP_UNUSED_F7                      0xf7
#define OP_UNUSED_F8                      0xf8
#define OP_UNUSED_F9                      0xf9
#define OP_INVOKE_POLYMORPHIC             0xfa //实现麻烦，不抽含有这个指令的方法
#define OP_INVOKE_POLYMORPHIC_RANGE       0xfb //实现麻烦，不抽含有这个指令的方法
#define OP_INVOKE_CUSTOM                  0xfc //实现麻烦，不抽含有这个指令的方法
#define OP_INVOKE_CUSTOM_RANGE            0xfd //实现麻烦，不抽含有这个指令的方法
#define OP_CONST_METHOD_HANDLE            0xfe //实现麻烦，不抽含有这个指令的方法
#define OP_CONST_METHOD_TYPE              0xff //实现麻烦，不抽含有这个指令的方法
#endif // ARK_VMP_OPCODE_DEF_H

